accounts/urls.py
from django.contrib.auth.views import (LogoutView, PasswordResetCompleteView,
                                       PasswordResetConfirmView,
                                       PasswordResetDoneView,
                                       PasswordResetView)
from django.urls import path

from . import views

urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('settings/', views.SettingsView.as_view(), name='settings'),
    path('change-password/', views.ChangePasswordView.as_view(),
         name='change_password'),

    path('password-reset/', PasswordResetView.as_view(
        template_name='accounts/password_reset.html'),
        name='password_reset'),
    path('password-reset/done/', PasswordResetDoneView.as_view(
         template_name='accounts/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
         template_name='accounts/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('reset/done', PasswordResetCompleteView.as_view(
         template_name='accounts/password_reset_complete.html'),
         name='password_reset_complete'),

]

charitydonation/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('charitydonation_app.urls')),
    path('user/', include('accounts.urls')),
]

charitydonation_app/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.LandingPageView.as_view(), name='index'),
    path('add-donation/', views.AddDonationView.as_view(), name='add_donation'),
    path('form-confirmation/', views.ConfirmationView.as_view(),
         name='form_confirmation'),
    path('institutions/', views.InstitutionsList.as_view(), name='institutions'),
    path('contact/', views.ContactView.as_view(), name='contact'),
]

charitydonation_app/models.py
from django.core.validators import MaxValueValidator, RegexValidator
from django.db import models
from django.utils import timezone

from accounts.models import User


class Category(models.Model):
    name = models.CharField(max_length=50)

    class Meta:
        ordering = ['id']
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name


class Institution(models.Model):
    KIND_CHOICES = (
        (0, 'fundacja'),
        (1, 'organizacja pozarządowa'),
        (2, 'zbiórka lokalna')
    )

    name = models.CharField(max_length=50)
    description = models.TextField()
    kind = models.IntegerField(choices=KIND_CHOICES, default=0)
    categories = models.ManyToManyField(Category)

    class Meta:
        ordering = ['id']

    def __str__(self):
        return self.name


class Donation(models.Model):
    quantity = models.PositiveIntegerField(validators=[MaxValueValidator(100)])
    categories = models.ManyToManyField(Category)
    institution = models.ForeignKey(Institution, on_delete=models.CASCADE)
    address = models.CharField(max_length=50)
    phone_number = models.CharField(max_length=30,
                                    validators=[
                                        RegexValidator(
                                            regex='(^|\W)(\(?(\+|00)?48\)?)?[ -]?\d{3}[ -]?\d{3}[ -]?\d{3}(?!\w)',
                                            message='Numer telefonu jest nieprawidłowy.')])
    city = models.CharField(max_length=50)
    zip_code = models.CharField(max_length=6,
                                validators=[
                                    RegexValidator(
                                        '[0-9]{2}\-[0-9]{3}',
                                        message='Kod pocztowy jest nieprawidłowy.')])
    pick_up_date = models.DateField()
    pick_up_time = models.TimeField()
    pick_up_comment = models.TextField(blank=True)
    is_taken = models.BooleanField(default=False)
    taken_date = models.DateField(blank=True, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        ordering = ['id']

    def save(self, *args, **kwargs):
        if self.is_taken and self.taken_date is None:
            self.taken_date = timezone.now()
        elif not self.is_taken and self.taken_date is not None:
            self.taken_date = None
        super().save(*args, **kwargs)

charitydonation_app/forms.py
from django import forms
from django.core.validators import RegexValidator
from django.utils.translation import gettext_lazy as _

from .models import Category, Donation, Institution


class DonationForm(forms.ModelForm):

    class Meta:
        model = Donation
        exclude = ('user',)


class ContactForm(forms.Form):
    name = forms.CharField(required=True, max_length=40, label='')
    surname = forms.CharField(required=True, max_length=40, label='')
    email = forms.EmailField(required=True, max_length=100, label='')
    message = forms.CharField(required=True, widget=forms.Textarea, label='')

charitydonation_app/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.mail import EmailMessage
from django.core.paginator import Paginator
from django.http import HttpResponse, JsonResponse
from django.shortcuts import redirect, render
from django.views import View

from accounts.models import User

from .forms import ContactForm, DonationForm
from .models import Category, Donation, Institution
from .serializers import InstitutionSerializer


class LandingPageView(View):

    def get(self, request):
        context = {}
        quantity = 0

        # Sum of all bags
        for donation in Donation.objects.values_list('quantity', flat=True):
            quantity += donation
        context['quantity'] = quantity
        context['institutions'] = Institution.objects.all()

        # Pagination for institutions
        foundations = Institution.objects.filter(kind=0)
        organizations = Institution.objects.filter(kind=1)
        local_collections = Institution.objects.filter(kind=2)

        paginator_foundations = Paginator(foundations, 5)
        first_page_foundations = paginator_foundations.page(1).object_list
        page_range_foundations = paginator_foundations.page_range
        sum_page_range_foundations = sum(page_range_foundations)

        paginator_organizations = Paginator(organizations, 5)
        first_page_organizations = paginator_organizations.page(1).object_list
        page_range_organizations = paginator_organizations.page_range
        sum_page_range_organizations = sum(page_range_organizations)

        paginator_local_collections = Paginator(local_collections, 5)
        first_page_local_collections = paginator_local_collections.page(
            1).object_list
        page_range_local_collections = paginator_local_collections.page_range
        sum_page_range_local_collections = sum(page_range_local_collections)

        context['first_page_foundations'] = first_page_foundations
        context['page_range_foundations'] = page_range_foundations
        context['sum_page_range_foundations'] = sum_page_range_foundations

        context['first_page_organizations'] = first_page_organizations
        context['page_range_organizations'] = page_range_organizations
        context['sum_page_range_organizations'] = sum_page_range_organizations

        context['first_page_local_collections'] = first_page_local_collections
        context['page_range_local_collections'] = page_range_local_collections
        context['sum_page_range_local_collections'] = sum_page_range_local_collections

        return render(request, 'charitydonation_app/index.html', context)

    def post(self, request):
        context = {}
        kind = request.POST.get('kind')
        institutions = Institution.objects.filter(kind=kind)
        paginator = Paginator(institutions, 5)
        page_number = request.POST.get('page')
        serializer = InstitutionSerializer(
            paginator.page(page_number).object_list, many=True)
        return JsonResponse(serializer.data, safe=False)


class AddDonationView(LoginRequiredMixin, View):

    def get(self, request):
        categories = Category.objects.all()
        return render(request, 'charitydonation_app/add_donation.html', {'categories': categories})

    def post(self, request):
        form = DonationForm(request.POST)
        if form.is_valid():
            donation = form.save(commit=False)
            donation.user = request.user
            donation.save()
            donation.categories.set(request.POST.getlist('categories'))
            return JsonResponse({'success': 'Success'})
        else:
            response = JsonResponse(form.errors.get_json_data())
            response.status_code = 422
            return response


class ConfirmationView(View):

    def post(self, request):
        return redirect('index')

    def get(self, request):
        return render(request, 'charitydonation_app/form_confirmation.html')


class InstitutionsList(View):

    def get(self, request):
        cat_ids = request.GET.getlist('category')
        if not cat_ids:
            return HttpResponse(status=204)
        institutions = Institution.objects.filter(categories=cat_ids[0])
        for cat_id in cat_ids[1:]:
            institutions = institutions.filter(categories=cat_id)
        serializer = InstitutionSerializer(institutions, many=True)
        return JsonResponse(serializer.data, safe=False)


class ContactView(View):

    def get(self, request):
        return redirect('index')

    def post(self, request):
        form = ContactForm(request.POST)
        context = {}
        if form.is_valid():
            mail_subject = 'Formularz kontaktowy'
            message = f'{request.POST.get("message")}\n{request.POST.get("email")}'
            superusers_emails = list(User.objects.filter(
                is_superuser=True).values_list('email', flat=True))
            to_email = 1
            email = EmailMessage(
                mail_subject, message, to=[superusers_emails]
            )
            email.send()
            context['message'] = ('Sukces!\nDziękujemy za twoją wiadomość.'
                                  '\nSpróbujemy skontaktować się z tobą jak najszybciej!')
            return render(request, 'charitydonation_app/blank_page.html', context)
        return render(request, 'charitydonation_app/contact_error.html')

charitydonation_app/templates/charitydonation_app/add_donation.html
{% extends 'charitydonation_app/base.html' %}
{% block header %}header--main-page{% endblock header %}
{% block slogan %}
      <div class="slogan container container--90">
        <div class="slogan--item">
          <h1>
            Oddaj rzeczy, których już nie chcesz<br />
            <span class="uppercase">potrzebującym</span>
          </h1>

          <div class="slogan--steps">
            <div class="slogan--steps-title">Wystarczą 4 proste kroki:</div>
            <ul class="slogan--steps-boxes">
              <li>
                <div><em>1</em><span>Wybierz rzeczy</span></div>
              </li>
              <li>
                <div><em>2</em><span>Spakuj je w worki</span></div>
              </li>
              <li>
                <div><em>3</em><span>Wybierz fundację</span></div>
              </li>
              <li>
                <div><em>4</em><span>Zamów kuriera</span></div>
              </li>
            </ul>
          </div>
        </div>
      </div>
{% endblock slogan %}
{% block section %}
    <section class="form--steps">
      <div class="form--steps-instructions">
        <div class="form--steps-container">
          <h3>Ważne!</h3>
          <p data-step="1" class="active">
            Uzupełnij szczegóły dotyczące Twoich rzeczy. Dzięki temu będziemy
            wiedzieć komu najlepiej je przekazać.
          </p>
          <p data-step="2">
            Uzupełnij szczegóły dotyczące Twoich rzeczy. Dzięki temu będziemy
            wiedzieć komu najlepiej je przekazać.
          </p>
          <p data-step="3">
           Wybierz jedną, do
            której trafi Twoja przesyłka.
          </p>
          <p data-step="4">Podaj adres oraz termin odbioru rzeczy.</p>
        </div>
      </div>

      <div class="form--steps-container">
        <div class="form--steps-counter">Krok <span>1</span>/5</div>

        <form method="post">
          <!-- STEP 1: class .active is switching steps -->
          <div data-step="1" class="active">
            <h3>Zaznacz co chcesz oddać:</h3>

            {% for category in categories %}
            <div class="form-group form-group--checkbox">
              <label>
                <input
                  type="checkbox"
                  name="categories"
                  value="{{ category.id }}"
                />
                <span class="checkbox"></span>
                <span class="description"
                  >{{ category.name }}</span
                >
              </label>
            </div>
            {% endfor %}

            <div class="form-group form-group--buttons">
              <button type="button" class="btn next-step">Dalej</button>
            </div>
          </div>

          <!-- STEP 2 -->
          <div data-step="2">
            <h3>Podaj liczbę 60l worków, w które spakowałeś/aś rzeczy:</h3>

            <div class="form-group form-group--inline">
              <label>
                Liczba 60l worków:
                <input type="number" name="bags" step="1" min="1"/>
              </label>
            </div>

            <div class="form-group form-group--buttons">
              <button type="button" class="btn prev-step">Wstecz</button>
              <button type="button" class="btn next-step">Dalej</button>
            </div>
          </div>



          <!-- STEP 3 -->
          <div data-step="3">
            <h3>Wybierz organizacje, której chcesz pomóc:</h3>

            <div class="form-group form-group--buttons">
              <button type="button" class="btn prev-step">Wstecz</button>
              <button type="button" class="btn next-step">Dalej</button>
            </div>
          </div>

          <!-- STEP 4 -->
          <div data-step="4">
            <h3>Podaj adres oraz termin odbioru rzecz przez kuriera:</h3>

            <div class="form-section form-section--columns">
              <div class="form-section--column">
                <h4>Adres odbioru</h4>
                <div class="form-group form-group--inline">
                  <label> Ulica <input type="text" name="address" /> </label>
                </div>

                <div class="form-group form-group--inline">
                  <label> Miasto <input type="text" name="city" /> </label>
                </div>

                <div class="form-group form-group--inline">
                  <label>
                    Kod pocztowy <input type="text" name="postcode" />
                  </label>
                </div>

                <div class="form-group form-group--inline">
                  <label>
                    Numer telefonu <input type="phone" name="phone" />
                  </label>
                </div>
              </div>

              <div class="form-section--column">
                <h4>Termin odbioru</h4>
                <div class="form-group form-group--inline">
                  <label> Data <input type="date" name="data" /> </label>
                </div>

                <div class="form-group form-group--inline">
                  <label> Godzina <input type="time" name="time" /> </label>
                </div>

                <div class="form-group form-group--inline">
                  <label>
                    Uwagi dla kuriera
                    <textarea name="more_info" rows="5"></textarea>
                  </label>
                </div>
              </div>
            </div>
            <div class="form-group form-group--buttons">
              <button type="button" class="btn prev-step">Wstecz</button>
              <button type="button" class="btn next-step">Dalej</button>
            </div>
          </div>

          <!-- STEP 5 -->
          <div data-step="5">
            <h3>Podsumowanie Twojej darowizny</h3>

            <div class="summary">
              <div class="form-section">
                <h4>Oddajesz:</h4>
                <ul>
                  <li>
                    <span class="icon icon-bag"></span>
                    <span class="summary--text"
                      ></span
                    >
                  </li>

                  <li>
                    <span class="icon icon-hand"></span>
                    <span class="summary--text"
                      ></span
                    >
                  </li>
                </ul>
              </div>

              <div class="form-section form-section--columns">
                <div class="form-section--column">
                  <h4>Adres odbioru:</h4>
                  <ul>
                  </ul>
                </div>

                <div class="form-section--column">
                  <h4>Termin odbioru:</h4>
                  <ul>
                  </ul>
                </div>
              </div>
            </div>

            <div class="form-group form-group--buttons">
              <button type="button" class="btn prev-step">Wstecz</button>
              <button type="submit" class="btn">Potwierdzam</button>
            </div>
          </div>
          <input type="hidden" name="user" value={{ user.id }} id="id_user">
        </form>
      </div>
    </section>
{% endblock section %}

charitydonation_app/templates/charitydonation_app/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pl">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'charitydonation_app/css/style.css' %}" />
  </head>
  <body>
    <header class="{% block header %}{% endblock header %}">
      <nav class="container container--70">
      {% if user.is_authenticated %}
        <ul class="nav--actions">
          <li class="logged-user">
            Witaj {{ user.first_name }}
            <ul class="dropdown">
              <li><a href="{% url 'profile' %}">Profil</a></li>
              <li><a href="{% url 'settings' %}">Ustawienia</a></li>
              {% if user.is_superuser %}
              <li><a href="/admin/">Administracja</a></li>
              {% endif %}
              <li><a href="{% url 'logout' %}">Wyloguj</a></li>
            </ul>
          </li>
        </ul>
      {% else %}
        <ul class="nav--actions">
          <li>
            <a href="{% url 'login' %}" class="btn btn--small btn--without-border">Zaloguj</a>
          </li>
          <li>
            <a href="{% url 'register' %}" class="btn btn--small btn--highlighted">Załóż konto</a>
          </li>
        </ul>
      {% endif %}

        <ul>
          <li><a href="{% url 'index' %}" class="btn btn--without-border active">Start</a></li>
          <li>
            <a href="/#steps" class="btn btn--without-border">O co chodzi?</a>
          </li>
          <li><a href="/#about-us" class="btn btn--without-border">O nas</a></li>
          <li>
            <a href="/#help" class="btn btn--without-border"
              >Fundacje i organizacje</a
            >
          </li>
          <li>
            <a href="{% url 'add_donation' %}" class="btn btn--without-border">Przekaż dary</a>
          </li>
          <li>
            <a href="/#contact" class="btn btn--without-border">Kontakt</a>
          </li>
        </ul>
      </nav>
      {% block slogan %}
      {% endblock slogan %}
    </header>
    {% block section %}
    {% endblock section %}
    <footer>
      <div id="contact" class="contact">
        <h2>Skontaktuj się z nami</h2>
        <h3>Formularz kontaktowy</h3>
        <form class="form--contact" method="POST" action="{% url 'contact' %}">
        {% csrf_token %}
          <div class="form-group form-group--50">
            <input type="text" name="name" placeholder="Imię" required />
          </div>
          <div class="form-group form-group--50">
            <input type="text" name="surname" placeholder="Nazwisko" required />
          </div>

          <div class="form-group">
            <input type="email" name="email" placeholder="Email" required />
          </div>

          <div class="form-group">
            <textarea
              name="message"
              placeholder="Wiadomość"
              rows="1"
              required
            ></textarea>
          </div>

          <button class="btn" type="submit">Wyślij</button>
        </form>
      </div>
      <div class="bottom-line">
        <span class="bottom-line--copy">Copyright &copy; 2020</span>
        <div class="bottom-line--icons">
          <a href="#" class="btn btn--small"
            ><img src="{% static 'charitydonation_app/images/icon-facebook.svg' %}"
          /></a>
          <a href="#" class="btn btn--small"
            ><img src="{% static 'charitydonation_app/images/icon-instagram.svg' %}"
          /></a>
        </div>
      </div>
    </footer>

    <script
			  src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.9/jquery.validate.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/js-cookie@rc/dist/js.cookie.min.js"></script>
    <script src="{% static 'charitydonation_app/js/app.js' %}"></script>
  </body>
</html>

charitydonation_app/templates/charitydonation_app/blank_page.html
{% extends 'charitydonation_app/base.html' %}
{% load static %}
{% block header %}header--form-page{% endblock header %}
{% block slogan %}
  <div class="message container container--90">
    <h2>
      {{ message|linebreaks }}
    </h2>
  </div>
{% endblock slogan %}

charitydonation_app/templates/charitydonation_app/form_confirmation.html
{% extends 'charitydonation_app/base.html' %}
{% load static %}
{% block header %}header--form-page{% endblock header %}
{% block slogan %}
  <div class="message container container--90">
    <h2>
      Dziękujemy za przesłanie formularza.
      <br>
      Na maila prześlemy wszelkie
      informacje o odbiorze.
    </h2>
  </div>
{% endblock slogan %}

charitydonation_app/templates/charitydonation_app/index.html
{% extends 'charitydonation_app/base.html' %}
{% load static %}
{% block header %}header--main-page{% endblock header %}
{% block slogan %}
    <div class="slogan container container--90">
      <div class="slogan--item">
        <h1>
          Zacznij pomagać!<br />
          Oddaj niechciane rzeczy w zaufane ręce
        </h1>
      </div>
    </div>
{% endblock slogan %}
{% block section %}
    <section id="stats" class="stats">
      <div class="container container--85">
        <div class="stats--item">
          <em>{{ quantity }}</em>
          <h3>Oddanych worków</h3>
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius est beatae, quod accusamus illum tempora!</p>
        </div>

        <div class="stats--item">
          <em>{{ institutions.count }}</em>
          <h3>Wspartych organizacji</h3>
          <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Laboriosam magnam, sint nihil cupiditate quas quam.</p>
        </div>

      </div>
    </section>

    <section id="steps" class="steps">
      <h2>Wystarczą 4 proste kroki</h2>

      <div class="steps--container">
        <div class="steps--item">
          <span class="icon icon--hands"></span>
          <h3>Wybierz rzeczy</h3>
          <p>ubrania, zabawki, sprzęt i inne</p>
        </div>
        <div class="steps--item">
          <span class="icon icon--arrow"></span>
          <h3>Spakuj je</h3>
          <p>skorzystaj z worków na śmieci</p>
        </div>
        <div class="steps--item">
          <span class="icon icon--glasses"></span>
          <h3>Zdecyduj komu chcesz pomóc</h3>
          <p>wybierz zaufane miejsce</p>
        </div>
        <div class="steps--item">
          <span class="icon icon--courier"></span>
          <h3>Zamów kuriera</h3>
          <p>kurier przyjedzie w dogodnym terminie</p>
        </div>
      </div>

      <a href="{% url 'register' %}" class="btn btn--large">Załóż konto</a>
    </section>

    <section id="about-us" class="about-us">
      <div class="about-us--text">
        <h2>O nas</h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptas vitae animi rem pariatur incidunt libero optio esse quisquam illo omnis.</p>
        <img src="{% static 'charitydonation_app/images/signature.svg' %}" class="about-us--text-signature" alt="Signature" />
      </div>
      <div class="about-us--image"><img src="{% static 'charitydonation_app/images/about-us.jpg' %}" alt="People in circle" /></div>
    </section>

     <section id="help" class="help">
      <h2>Komu pomagamy?</h2>

      <ul class="help--buttons">
        <li data-id="1"><a href="#" class="btn btn--without-border active">Fundacjom</a></li>
        <li data-id="2"><a href="#" class="btn btn--without-border">Organizacjom pozarządowym</a></li>
        <li data-id="3"><a href="#" class="btn btn--without-border">Lokalnym zbiórkom</a></li>
      </ul>

      <!-- SLIDE 1 -->
      <div class="help--slides active" data-id="1">
        <p>W naszej bazie znajdziesz listę zweryfikowanych Fundacji, z którymi współpracujemy. Możesz sprawdzić czym się zajmują, komu pomagają i czego potrzebują.</p>

        <ul class="help--slides-items">
        {% for foundation in first_page_foundations %}
          <li>
            <div class="col">
              <div class="title">Fundacja "{{ foundation }}"</div>
              <div class="subtitle">
                Cel i misja: {{ foundation.description|slice:":110" }}{% if foundation.description|length > 110 %}&hellip;{% endif %}
              </div>
            </div>

            <div class="col"><div class="text">
            {% for category in foundation.categories.all %}
            {% if forloop.last %}
              {{ category }}
            {% else %}
              {{ category }}, 
            {% endif %}
            {% endfor %}
            </div></div>
          </li>
        {% endfor %}
        </ul>

        {% if sum_page_range_foundations > 1 %}
        <ul class="help--slides-pagination">
          {% for page in page_range_foundations %}
            {% if forloop.first %}
              <li><a href="#" class="btn btn--small btn--without-border active" data-page="{{ page }}">{{ page }}</a></li>
            {% else %}
              <li><a href="#" class="btn btn--small btn--without-border" data-page="{{ page }}">{{ page }}</a></li>
            {% endif %}
          {% endfor %}
        </ul>
        {% endif %}
       
      </div>


      <!-- SLIDE 2 -->
      <div class="help--slides" data-id="2">
        <p>
          Lorem ipsum dolor, sit amet consectetur adipisicing elit. Hic officiis mollitia dolor, neque aspernatur accusamus debitis. Ducimus, officia. Quia, sunt illum! Non iste placeat ab ipsum alias
          quos suscipit corporis!
        </p>
        <ul class="help--slides-items">
        {% for organization in first_page_organizations %}
          <li>
            <div class="col">
              <div class="title">Organizacja "{{ organization }}"</div>
              <div class="subtitle">
                Cel i misja: {{ organization.description|slice:":110" }}{% if organization.description|length > 110 %}&hellip;{% endif %}
              </div>
            </div>

            <div class="col"><div class="text">
            {% for category in organization.categories.all %}
              {% if forloop.last %}
                {{ category }}
              {% else %}
                {{ category }}, 
              {% endif %}
            {% endfor %}
            </div></div>
          </li>
        {% endfor %}
        </ul>

        {% if sum_page_range_organizations > 1 %}
        <ul class="help--slides-pagination">
          {% for page in page_range_organizations %}
            {% if forloop.first %}
              <li><a href="#" class="btn btn--small btn--without-border active" data-page="{{ page }}">{{ page }}</a></li>
            {% else %}
              <li><a href="#" class="btn btn--small btn--without-border" data-page="{{ page }}">{{ page }}</a></li>
            {% endif %}
          {% endfor %}
        </ul>
        {% endif %}

      </div>

      <!-- SLIDE 3 -->
      <div class="help--slides" data-id="3">
        <p>Lorem ipsum dolor sit amet, his ocurreret persequeris ea, ad utinam laudem duo. Verterem adipisci partiendo eos ne, ea his reque quaeque recteque, ne quo lobortis intellegam.</p>
        <ul class="help--slides-items">
        {% for local in first_page_local_collections %}
          <li>
            <div class="col">
              <div class="title">Lokalna zbiórka "{{ local }}"</div>
              <div class="subtitle">
                Cel i misja: {{ local.description|slice:":110" }}{% if local.description|length > 110 %}&hellip;{% endif %}
              </div>
            </div>

            <div class="col"><div class="text">
            {% for category in local.categories.all %}
            {% if forloop.last %}
              {{ category }}
            {% else %}
              {{ category }}, 
            {% endif %}
            {% endfor %}
            </div></div>
          </li>
        {% endfor %}
        </ul>

        {% if sum_page_range_local_collections > 1 %}
        <ul class="help--slides-pagination">
          {% for page in page_range_local_collections %}
            {% if forloop.first %}
              <li><a href="#" class="btn btn--small btn--without-border active" data-page="{{ page }}">{{ page }}</a></li>
            {% else %}
              <li><a href="#" class="btn btn--small btn--without-border" data-page="{{ page }}">{{ page }}</a></li>
            {% endif %}
          {% endfor %}
        </ul>
        {% endif %}
        
      </div>
    </section>
{% endblock section %}